### ISSUE TITLE
Delegate is overridden on `register(scrollView:)`

### ISSUE THREAD

**Issue by stonko1994** [stonko1994/SimultaneouslyScrollView#1]
### Current behaviour
When passing a `UIScrollView` to the `SimultaneouslyScrollViewHandler` using the `register(scrollView:)` method, a potentially already set delegate will be overridden.

### Expected behaviour
An already set delegate should not be overridden when registering a `UIScrollView`.

**Comment by amoshsueh** [comment]
Hi, is any idea to fix this issue? Thanks!

**Comment by stonko1994** [comment]
One approach could be to store the `delegate` (if any) inside the `SimultaneouslyScrollViewHandler` and delegate all delegate calls to it.

**Comment by stonko1994** [comment]
> SwiftUI already sets a delegate on UIScrollView called SwiftUI.ScrollViewHelper.

that's interesting 👀. wasn't aware of this 🤔 maybe it's time to keep the original delegate and proxy through to it.

**Comment by julasamer** [comment]
I've implemented a solution; maybe I have time to create a pull request later in the evening. It doesn't help if someone else sets the delegate later on though, but in my brief testing that hasn't happened.

**Comment by stonko1994** [comment]
that would be awesome 🙌

**Comment by julasamer** [comment]
Took me a day longer, but I've submitted my pull request.

By the way, the reason why I started to investigate is because of my use case: I basically have a layout like in a spreadsheet application. A scrollview for the row headers that only scroll vertically, a scrollview for the column headers that only scroll horizontally, and a grid of cells that scroll both ways. The grid of cells needs to be synced to two other scroll views using two different handlers. That didn't work prior to adding the multicast delegate stuff.
