### ISSUE TITLE
Bitcode is not there

### ISSUE THREAD

**Issue by shivamican** [stonko1994/SimultaneouslyScrollView#13]

**Comment by stonko1994** [comment]
Hi @shivamican,

Bitcode is deprecated since Xcode 14 ([ref](https://developer.apple.com/documentation/xcode-release-notes/xcode-14-release-notes#Deprecations)).

Also, there is no option to enable Bitcode for a SPM package (at least not that I'm aware of). And since I have no plans to ship this framework as pre-compile binary, bitcode will never be included.

I would suggest to double check if you still need to have Bitcode enabled or if you can also disable it for your App.
